ALTER TABLE `User`
    MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN', 'DEPT_ADMIN', 'TEACHER', 'STUDENT') NOT NULL DEFAULT 'STUDENT';

ALTER TABLE `Organization`
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE';
